# CloudBuildの設定ファイル
steps:
  # Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/oracledraw:$COMMIT_SHA', '.']

  # ビルドしたイメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/oracledraw:$COMMIT_SHA']

  # CloudRunにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'oracledraw'
      - '--image=gcr.io/$PROJECT_ID/oracledraw:$COMMIT_SHA'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=cr-db-master@kawara-board.iam.gserviceaccount.com'

# ビルドしたイメージを保存
images:
  - 'gcr.io/$PROJECT_ID/oracledraw:$COMMIT_SHA'
